# Source: bucketrepo/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bucketrepo
  labels:
    chart: "bucketrepo-0.6.1"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: 'kubernetes.io/ingress.class: nginx'
    meta.helm.sh/release-name: 'bucketrepo'
    meta.helm.sh/release-namespace: 'jx'
  namespace: jx
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: bucketrepo-bucketrepo
