# Source: jx-preview/templates/gc-jobs-rb.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jx-preview-gc-jobs
  annotations:
    meta.helm.sh/release-name: 'jx-preview'
    meta.helm.sh/release-namespace: 'jx'
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jx-preview-gc-jobs
subjects:
- kind: ServiceAccount
  name: jx-preview-gc-jobs
