apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        yunhai20082008/jenkinsx: true
        yunhai20082008/sdasddda: true
        yunhai20082008/test-golang2: true
        yunhai20082008/test_golang: true
        yunhai20082008/test_jenkins_py: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        yunhai20082008/jenkinsx: merge
        yunhai20082008/sdasddda: merge
        yunhai20082008/test-golang2: merge
        yunhai20082008/test_golang: merge
        yunhai20082008/test_jenkins_py: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - yunhai20082008/jenkinsx
        - yunhai20082008/sdasddda
        - yunhai20082008/test_golang
        - yunhai20082008/test-golang2
        - yunhai20082008/test_jenkins_py
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - yunhai20082008/jenkinsx
        - yunhai20082008/sdasddda
        - yunhai20082008/test_golang
        - yunhai20082008/test-golang2
        - yunhai20082008/test_jenkins_py
      target_url: http://lighthouse-jx.192.168.59.103.nip.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
