apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: yunhai20082008
    provider: github
    repository: sdasdasd
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: yunhai20082008-sdasdasd
  namespace: jx
spec:
  httpCloneURL: https://github.com/yunhai20082008/sdasdasd.git
  org: yunhai20082008
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: sdasdasd
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/yunhai20082008/sdasdasd
