# Source: jxboot-helmfile-resources/templates/jx-gcjobs-cr.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gcjobs
  annotations:
    meta.helm.sh/release-name: 'jxboot-helmfile-resources'
    meta.helm.sh/release-namespace: 'jx'
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - delete
  - list
