# Source: lighthouse/templates/webhooks-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hook
  labels:
    chart: "lighthouse-1.23.4"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'lighthouse'
    meta.helm.sh/release-namespace: 'jx'
  namespace: jx
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: lighthouse-webhooks
