# Source: lighthouse/templates/config-external-plugins.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: lighthouse-external-plugins
  labels:
    app: lighthouse-lighthouse
    chart: "lighthouse-1.23.4"
    release: "lighthouse"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'lighthouse'
    meta.helm.sh/release-namespace: 'jx'
  namespace: jx
data:
  config.yaml: |-
    - name: cd-indicators
      requiredResources:
      - kind: Service
        name: cd-indicators
        namespace: jx
    - name: lighthouse-webui-plugin
      requiredResources:
      - kind: Service
        name: lighthouse-webui-plugin
        namespace: jx
